//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 11:04:38 AM CEST 
//


package cz.petrbalat.xml.ares;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cast_obce_RFO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="cast_obce_RFO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="KCO" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3}kod_casti_obce" minOccurs="0"/>
 *         &lt;element name="Nazev" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3}nazev_casti_obce" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cast_obce_RFO", propOrder = {
  "kco",
  "nazev"
})
public class CastObceRFO {

  @XmlElement(name = "KCO")
  protected String kco;
  @XmlElement(name = "Nazev")
  protected String nazev;

  /**
   * Gets the value of the kco property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getKCO() {
    return kco;
  }

  /**
   * Sets the value of the kco property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setKCO(String value) {
    this.kco = value;
  }

  /**
   * Gets the value of the nazev property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getNazev() {
    return nazev;
  }

  /**
   * Sets the value of the nazev property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setNazev(String value) {
    this.nazev = value;
  }

}
