//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 11:04:38 AM CEST 
//


package cz.petrbalat.xml.ares;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Informace o chybě včetně krátké nápovědy
 *
 * <p>Java class for chyba complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="chyba">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="K" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Popis" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3}popis"/>
 *         &lt;element name="Napoveda" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3}popis"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "chyba", propOrder = {
  "k",
  "popis",
  "napoveda"
})
public class Chyba {

  @XmlElement(name = "K", required = true)
  protected String k;
  @XmlElement(name = "Popis", required = true)
  protected String popis;
  @XmlElement(name = "Napoveda", required = true)
  protected String napoveda;

  /**
   * Gets the value of the k property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getK() {
    return k;
  }

  /**
   * Sets the value of the k property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setK(String value) {
    this.k = value;
  }

  /**
   * Gets the value of the popis property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getPopis() {
    return popis;
  }

  /**
   * Sets the value of the popis property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setPopis(String value) {
    this.popis = value;
  }

  /**
   * Gets the value of the napoveda property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getNapoveda() {
    return napoveda;
  }

  /**
   * Sets the value of the napoveda property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setNapoveda(String value) {
    this.napoveda = value;
  }

}
