//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 11:04:38 AM CEST 
//


package cz.petrbalat.xml.ares;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Jeden cizí název obchodní firmy
 *
 * <p>Java class for cizi_nazev complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="cizi_nazev">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Nazev" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3}obchodni_firma"/>
 *         &lt;element name="Jazyk" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="dod" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="ddo" type="{http://www.w3.org/2001/XMLSchema}date" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cizi_nazev", propOrder = {
  "nazev",
  "jazyk"
})
public class CiziNazev {

  @XmlElement(name = "Nazev", required = true)
  protected String nazev;
  @XmlElement(name = "Jazyk", required = true)
  protected String jazyk;
  @XmlAttribute(name = "dod")
  @XmlSchemaType(name = "date")
  protected XMLGregorianCalendar dod;
  @XmlAttribute(name = "ddo")
  @XmlSchemaType(name = "date")
  protected XMLGregorianCalendar ddo;

  /**
   * Gets the value of the nazev property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getNazev() {
    return nazev;
  }

  /**
   * Sets the value of the nazev property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setNazev(String value) {
    this.nazev = value;
  }

  /**
   * Gets the value of the jazyk property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getJazyk() {
    return jazyk;
  }

  /**
   * Sets the value of the jazyk property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setJazyk(String value) {
    this.jazyk = value;
  }

  /**
   * Gets the value of the dod property.
   *
   * @return possible object is
   * {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getDod() {
    return dod;
  }

  /**
   * Sets the value of the dod property.
   *
   * @param value allowed object is
   *              {@link XMLGregorianCalendar }
   */
  public void setDod(XMLGregorianCalendar value) {
    this.dod = value;
  }

  /**
   * Gets the value of the ddo property.
   *
   * @return possible object is
   * {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getDdo() {
    return ddo;
  }

  /**
   * Sets the value of the ddo property.
   *
   * @param value allowed object is
   *              {@link XMLGregorianCalendar }
   */
  public void setDdo(XMLGregorianCalendar value) {
    this.ddo = value;
  }

}
