//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 11:04:38 AM CEST 
//


package cz.petrbalat.xml.ares;

import javax.xml.bind.annotation.*;


/**
 * Institucionární sektor (RES)
 *
 * <p>Java class for institucionarni_sektor complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="institucionarni_sektor">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="zdroj" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}zdroj_type" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "institucionarni_sektor", propOrder = {
  "value"
})
public class InstitucionarniSektor {

  @XmlValue
  protected String value;
  @XmlAttribute(name = "zdroj")
  protected ZdrojType zdroj;

  /**
   * Gets the value of the value property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getValue() {
    return value;
  }

  /**
   * Sets the value of the value property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setValue(String value) {
    this.value = value;
  }

  /**
   * Gets the value of the zdroj property.
   *
   * @return possible object is
   * {@link ZdrojType }
   */
  public ZdrojType getZdroj() {
    return zdroj;
  }

  /**
   * Sets the value of the zdroj property.
   *
   * @param value allowed object is
   *              {@link ZdrojType }
   */
  public void setZdroj(ZdrojType value) {
    this.zdroj = value;
  }

}
