//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 11:04:38 AM CEST 
//


package cz.petrbalat.xml.ares;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the cz.petrbalat.xml.ares package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

  private final static QName _EList_QNAME = new QName("http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3", "E_list");

  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cz.petrbalat.xml.ares
   */
  public ObjectFactory() {
  }

  /**
   * Create an instance of {@link XsltErrorList }
   */
  public XsltErrorList createXsltErrorList() {
    return new XsltErrorList();
  }

  /**
   * Create an instance of {@link Akcie }
   */
  public Akcie createAkcie() {
    return new Akcie();
  }

  /**
   * Create an instance of {@link OdstepneZavody }
   */
  public OdstepneZavody createOdstepneZavody() {
    return new OdstepneZavody();
  }

  /**
   * Create an instance of {@link KonkurzyVyrovnani }
   */
  public KonkurzyVyrovnani createKonkurzyVyrovnani() {
    return new KonkurzyVyrovnani();
  }

  /**
   * Create an instance of {@link AresOdpovedi }
   */
  public AresOdpovedi createAresOdpovedi() {
    return new AresOdpovedi();
  }

  /**
   * Create an instance of {@link OdpovedRES }
   */
  public OdpovedRES createOdpovedRES() {
    return new OdpovedRES();
  }

  /**
   * Create an instance of {@link ChybovaOdpoved }
   */
  public ChybovaOdpoved createChybovaOdpoved() {
    return new ChybovaOdpoved();
  }

  /**
   * Create an instance of {@link Uvod }
   */
  public Uvod createUvod() {
    return new Uvod();
  }

  /**
   * Create an instance of {@link VysledekHledani }
   */
  public VysledekHledani createVysledekHledani() {
    return new VysledekHledani();
  }

  /**
   * Create an instance of {@link ZakladniUdajeRZP }
   */
  public ZakladniUdajeRZP createZakladniUdajeRZP() {
    return new ZakladniUdajeRZP();
  }

  /**
   * Create an instance of {@link CastObceRFO }
   */
  public CastObceRFO createCastObceRFO() {
    return new CastObceRFO();
  }

  /**
   * Create an instance of {@link FinancniUrad }
   */
  public FinancniUrad createFinancniUrad() {
    return new FinancniUrad();
  }

  /**
   * Create an instance of {@link Vklad }
   */
  public Vklad createVklad() {
    return new Vklad();
  }

  /**
   * Create an instance of {@link RadkyTextuUsneseni }
   */
  public RadkyTextuUsneseni createRadkyTextuUsneseni() {
    return new RadkyTextuUsneseni();
  }

  /**
   * Create an instance of {@link VkladSpolecnika }
   */
  public VkladSpolecnika createVkladSpolecnika() {
    return new VkladSpolecnika();
  }

  /**
   * Create an instance of {@link TypZmeny }
   */
  public TypZmeny createTypZmeny() {
    return new TypZmeny();
  }

  /**
   * Create an instance of {@link Zivnost }
   */
  public Zivnost createZivnost() {
    return new Zivnost();
  }

  /**
   * Create an instance of {@link ZrizovatelePR }
   */
  public ZrizovatelePR createZrizovatelePR() {
    return new ZrizovatelePR();
  }

  /**
   * Create an instance of {@link SpisovaZnacka }
   */
  public SpisovaZnacka createSpisovaZnacka() {
    return new SpisovaZnacka();
  }

  /**
   * Create an instance of {@link ZakladateleOPS }
   */
  public ZakladateleOPS createZakladateleOPS() {
    return new ZakladateleOPS();
  }

  /**
   * Create an instance of {@link TextType }
   */
  public TextType createTextType() {
    return new TextType();
  }

  /**
   * Create an instance of {@link SubjektCEU }
   */
  public SubjektCEU createSubjektCEU() {
    return new SubjektCEU();
  }

  /**
   * Create an instance of {@link VypisRcns }
   */
  public VypisRcns createVypisRcns() {
    return new VypisRcns();
  }

  /**
   * Create an instance of {@link OdpovedCns }
   */
  public OdpovedCns createOdpovedCns() {
    return new OdpovedCns();
  }

  /**
   * Create an instance of {@link ZakladniUdajeRZZ }
   */
  public ZakladniUdajeRZZ createZakladniUdajeRZZ() {
    return new ZakladniUdajeRZZ();
  }

  /**
   * Create an instance of {@link ZakladniUdajeRCNS }
   */
  public ZakladniUdajeRCNS createZakladniUdajeRCNS() {
    return new ZakladniUdajeRCNS();
  }

  /**
   * Create an instance of {@link Organ }
   */
  public Organ createOrgan() {
    return new Organ();
  }

  /**
   * Create an instance of {@link ZakladniUdajeCNS }
   */
  public ZakladniUdajeCNS createZakladniUdajeCNS() {
    return new ZakladniUdajeCNS();
  }

  /**
   * Create an instance of {@link ZrizovateleOZ }
   */
  public ZrizovateleOZ createZrizovateleOZ() {
    return new ZrizovateleOZ();
  }

  /**
   * Create an instance of {@link StavKVZ }
   */
  public StavKVZ createStavKVZ() {
    return new StavKVZ();
  }

  /**
   * Create an instance of {@link DozorciRada }
   */
  public DozorciRada createDozorciRada() {
    return new DozorciRada();
  }

  /**
   * Create an instance of {@link Chyba }
   */
  public Chyba createChyba() {
    return new Chyba();
  }

  /**
   * Create an instance of {@link Konkurz }
   */
  public Konkurz createKonkurz() {
    return new Konkurz();
  }

  /**
   * Create an instance of {@link OstatniSkutecnosti }
   */
  public OstatniSkutecnosti createOstatniSkutecnosti() {
    return new OstatniSkutecnosti();
  }

  /**
   * Create an instance of {@link Stav }
   */
  public Stav createStav() {
    return new Stav();
  }

  /**
   * Create an instance of {@link VypisCNS }
   */
  public VypisCNS createVypisCNS() {
    return new VypisCNS();
  }

  /**
   * Create an instance of {@link OdpovedOR }
   */
  public OdpovedOR createOdpovedOR() {
    return new OdpovedOR();
  }

  /**
   * Create an instance of {@link KategoriePoctuPracovniku }
   */
  public KategoriePoctuPracovniku createKategoriePoctuPracovniku() {
    return new KategoriePoctuPracovniku();
  }

  /**
   * Create an instance of {@link RediteleOps }
   */
  public RediteleOps createRediteleOps() {
    return new RediteleOps();
  }

  /**
   * Create an instance of {@link UdajeKVZ }
   */
  public UdajeKVZ createUdajeKVZ() {
    return new UdajeKVZ();
  }

  /**
   * Create an instance of {@link AdresaARES }
   */
  public AdresaARES createAdresaARES() {
    return new AdresaARES();
  }

  /**
   * Create an instance of {@link Spravce }
   */
  public Spravce createSpravce() {
    return new Spravce();
  }

  /**
   * Create an instance of {@link SpolecniciBezVkladu }
   */
  public SpolecniciBezVkladu createSpolecniciBezVkladu() {
    return new SpolecniciBezVkladu();
  }

  /**
   * Create an instance of {@link VkAdresa }
   */
  public VkAdresa createVkAdresa() {
    return new VkAdresa();
  }

  /**
   * Create an instance of {@link TypFyzickeOsoby }
   */
  public TypFyzickeOsoby createTypFyzickeOsoby() {
    return new TypFyzickeOsoby();
  }

  /**
   * Create an instance of {@link ShodaRC }
   */
  public ShodaRC createShodaRC() {
    return new ShodaRC();
  }

  /**
   * Create an instance of {@link Texty }
   */
  public Texty createTexty() {
    return new Texty();
  }

  /**
   * Create an instance of {@link Dic }
   */
  public Dic createDic() {
    return new Dic();
  }

  /**
   * Create an instance of {@link Aceu }
   */
  public Aceu createAceu() {
    return new Aceu();
  }

  /**
   * Create an instance of {@link KrajRFO }
   */
  public KrajRFO createKrajRFO() {
    return new KrajRFO();
  }

  /**
   * Create an instance of {@link Cinnosti }
   */
  public Cinnosti createCinnosti() {
    return new Cinnosti();
  }

  /**
   * Create an instance of {@link StadrsDotaz }
   */
  public StadrsDotaz createStadrsDotaz() {
    return new StadrsDotaz();
  }

  /**
   * Create an instance of {@link DalsiUdaje }
   */
  public DalsiUdaje createDalsiUdaje() {
    return new DalsiUdaje();
  }

  /**
   * Create an instance of {@link Zuj }
   */
  public Zuj createZuj() {
    return new Zuj();
  }

  /**
   * Create an instance of {@link VypisOR }
   */
  public VypisOR createVypisOR() {
    return new VypisOR();
  }

  /**
   * Create an instance of {@link Ico }
   */
  public Ico createIco() {
    return new Ico();
  }

  /**
   * Create an instance of {@link ShodaOF }
   */
  public ShodaOF createShodaOF() {
    return new ShodaOF();
  }

  /**
   * Create an instance of {@link ZakladniUdajeOR }
   */
  public ZakladniUdajeOR createZakladniUdajeOR() {
    return new ZakladniUdajeOR();
  }

  /**
   * Create an instance of {@link OborCinnosti }
   */
  public OborCinnosti createOborCinnosti() {
    return new OborCinnosti();
  }

  /**
   * Create an instance of {@link Angazma }
   */
  public Angazma createAngazma() {
    return new Angazma();
  }

  /**
   * Create an instance of {@link Udalost }
   */
  public Udalost createUdalost() {
    return new Udalost();
  }

  /**
   * Create an instance of {@link KontrolniKomise }
   */
  public KontrolniKomise createKontrolniKomise() {
    return new KontrolniKomise();
  }

  /**
   * Create an instance of {@link Jmeni }
   */
  public Jmeni createJmeni() {
    return new Jmeni();
  }

  /**
   * Create an instance of {@link OboryCinnosti }
   */
  public OboryCinnosti createOboryCinnosti() {
    return new OboryCinnosti();
  }

  /**
   * Create an instance of {@link NadacniFond }
   */
  public NadacniFond createNadacniFond() {
    return new NadacniFond();
  }

  /**
   * Create an instance of {@link OdpovedRZZ }
   */
  public OdpovedRZZ createOdpovedRZZ() {
    return new OdpovedRZZ();
  }

  /**
   * Create an instance of {@link TypZdravotnickehoZarizeni }
   */
  public TypZdravotnickehoZarizeni createTypZdravotnickehoZarizeni() {
    return new TypZdravotnickehoZarizeni();
  }

  /**
   * Create an instance of {@link Prokura }
   */
  public Prokura createProkura() {
    return new Prokura();
  }

  /**
   * Create an instance of {@link Udalosti }
   */
  public Udalosti createUdalosti() {
    return new Udalosti();
  }

  /**
   * Create an instance of {@link OdpovedRZP }
   */
  public OdpovedRZP createOdpovedRZP() {
    return new OdpovedRZP();
  }

  /**
   * Create an instance of {@link ShodaICO }
   */
  public ShodaICO createShodaICO() {
    return new ShodaICO();
  }

  /**
   * Create an instance of {@link StavSubjektuCeu }
   */
  public StavSubjektuCeu createStavSubjektuCeu() {
    return new StavSubjektuCeu();
  }

  /**
   * Create an instance of {@link StatistickeUdaje }
   */
  public StatistickeUdaje createStatistickeUdaje() {
    return new StatistickeUdaje();
  }

  /**
   * Create an instance of {@link KChyba }
   */
  public KChyba createKChyba() {
    return new KChyba();
  }

  /**
   * Create an instance of {@link Spolecnik }
   */
  public Spolecnik createSpolecnik() {
    return new Spolecnik();
  }

  /**
   * Create an instance of {@link KKonkurz }
   */
  public KKonkurz createKKonkurz() {
    return new KKonkurz();
  }

  /**
   * Create an instance of {@link Slovo }
   */
  public Slovo createSlovo() {
    return new Slovo();
  }

  /**
   * Create an instance of {@link Nadace }
   */
  public Nadace createNadace() {
    return new Nadace();
  }

  /**
   * Create an instance of {@link Szo }
   */
  public Szo createSzo() {
    return new Szo();
  }

  /**
   * Create an instance of {@link MestskaCastRFO }
   */
  public MestskaCastRFO createMestskaCastRFO() {
    return new MestskaCastRFO();
  }

  /**
   * Create an instance of {@link RegistraceRZP }
   */
  public RegistraceRZP createRegistraceRZP() {
    return new RegistraceRZP();
  }

  /**
   * Create an instance of {@link Clen }
   */
  public Clen createClen() {
    return new Clen();
  }

  /**
   * Create an instance of {@link Druzstevnici }
   */
  public Druzstevnici createDruzstevnici() {
    return new Druzstevnici();
  }

  /**
   * Create an instance of {@link OkresRFO }
   */
  public OkresRFO createOkresRFO() {
    return new OkresRFO();
  }

  /**
   * Create an instance of {@link ErrorARES }
   */
  public ErrorARES createErrorARES() {
    return new ErrorARES();
  }

  /**
   * Create an instance of {@link KEksubj }
   */
  public KEksubj createKEksubj() {
    return new KEksubj();
  }

  /**
   * Create an instance of {@link Revizori }
   */
  public Revizori createRevizori() {
    return new Revizori();
  }

  /**
   * Create an instance of {@link SeznamNavracenych }
   */
  public SeznamNavracenych createSeznamNavracenych() {
    return new SeznamNavracenych();
  }

  /**
   * Create an instance of {@link Likvidace }
   */
  public Likvidace createLikvidace() {
    return new Likvidace();
  }

  /**
   * Create an instance of {@link InstitucionarniSektor }
   */
  public InstitucionarniSektor createInstitucionarniSektor() {
    return new InstitucionarniSektor();
  }

  /**
   * Create an instance of {@link ObchodniFirma }
   */
  public ObchodniFirma createObchodniFirma() {
    return new ObchodniFirma();
  }

  /**
   * Create an instance of {@link VypisRFO }
   */
  public VypisRFO createVypisRFO() {
    return new VypisRFO();
  }

  /**
   * Create an instance of {@link Stadrs }
   */
  public Stadrs createStadrs() {
    return new Stadrs();
  }

  /**
   * Create an instance of {@link FyzickaOsoba }
   */
  public FyzickaOsoba createFyzickaOsoba() {
    return new FyzickaOsoba();
  }

  /**
   * Create an instance of {@link Trvani }
   */
  public Trvani createTrvani() {
    return new Trvani();
  }

  /**
   * Create an instance of {@link Okec }
   */
  public Okec createOkec() {
    return new Okec();
  }

  /**
   * Create an instance of {@link NastupciZrizovatele }
   */
  public NastupciZrizovatele createNastupciZrizovatele() {
    return new NastupciZrizovatele();
  }

  /**
   * Create an instance of {@link VypisRES }
   */
  public VypisRES createVypisRES() {
    return new VypisRES();
  }

  /**
   * Create an instance of {@link PravniForma }
   */
  public PravniForma createPravniForma() {
    return new PravniForma();
  }

  /**
   * Create an instance of {@link DoplnujiciPravniFormy }
   */
  public DoplnujiciPravniFormy createDoplnujiciPravniFormy() {
    return new DoplnujiciPravniFormy();
  }

  /**
   * Create an instance of {@link Predstavenstvo }
   */
  public Predstavenstvo createPredstavenstvo() {
    return new Predstavenstvo();
  }

  /**
   * Create an instance of {@link Nace }
   */
  public Nace createNace() {
    return new Nace();
  }

  /**
   * Create an instance of {@link Organy }
   */
  public Organy createOrgany() {
    return new Organy();
  }

  /**
   * Create an instance of {@link VypisCeu }
   */
  public VypisCeu createVypisCeu() {
    return new VypisCeu();
  }

  /**
   * Create an instance of {@link OdpovedRcns }
   */
  public OdpovedRcns createOdpovedRcns() {
    return new OdpovedRcns();
  }

  /**
   * Create an instance of {@link Kapital }
   */
  public Kapital createKapital() {
    return new Kapital();
  }

  /**
   * Create an instance of {@link KZruseno }
   */
  public KZruseno createKZruseno() {
    return new KZruseno();
  }

  /**
   * Create an instance of {@link VypisBasic }
   */
  public VypisBasic createVypisBasic() {
    return new VypisBasic();
  }

  /**
   * Create an instance of {@link PenezniSuma }
   */
  public PenezniSuma createPenezniSuma() {
    return new PenezniSuma();
  }

  /**
   * Create an instance of {@link AdresaUIRSNazvy }
   */
  public AdresaUIRSNazvy createAdresaUIRSNazvy() {
    return new AdresaUIRSNazvy();
  }

  /**
   * Create an instance of {@link ZrizovateleNadace }
   */
  public ZrizovateleNadace createZrizovateleNadace() {
    return new ZrizovateleNadace();
  }

  /**
   * Create an instance of {@link VkPodnet }
   */
  public VkPodnet createVkPodnet() {
    return new VkPodnet();
  }

  /**
   * Create an instance of {@link Splaceno }
   */
  public Splaceno createSplaceno() {
    return new Splaceno();
  }

  /**
   * Create an instance of {@link ZakladniUdajeRES }
   */
  public ZakladniUdajeRES createZakladniUdajeRES() {
    return new ZakladniUdajeRES();
  }

  /**
   * Create an instance of {@link Msp }
   */
  public Msp createMsp() {
    return new Msp();
  }

  /**
   * Create an instance of {@link KKlic }
   */
  public KKlic createKKlic() {
    return new KKlic();
  }

  /**
   * Create an instance of {@link Sok }
   */
  public Sok createSok() {
    return new Sok();
  }

  /**
   * Create an instance of {@link KCosoba }
   */
  public KCosoba createKCosoba() {
    return new KCosoba();
  }

  /**
   * Create an instance of {@link Sop }
   */
  public Sop createSop() {
    return new Sop();
  }

  /**
   * Create an instance of {@link SpravceKonkurzuCEU }
   */
  public SpravceKonkurzuCEU createSpravceKonkurzuCEU() {
    return new SpravceKonkurzuCEU();
  }

  /**
   * Create an instance of {@link Sos }
   */
  public Sos createSos() {
    return new Sos();
  }

  /**
   * Create an instance of {@link TypRegistru }
   */
  public TypRegistru createTypRegistru() {
    return new TypRegistru();
  }

  /**
   * Create an instance of {@link Akcionari }
   */
  public Akcionari createAkcionari() {
    return new Akcionari();
  }

  /**
   * Create an instance of {@link VypisRZP }
   */
  public VypisRZP createVypisRZP() {
    return new VypisRZP();
  }

  /**
   * Create an instance of {@link VysledekDotazu }
   */
  public VysledekDotazu createVysledekDotazu() {
    return new VysledekDotazu();
  }

  /**
   * Create an instance of {@link TxtKVZ }
   */
  public TxtKVZ createTxtKVZ() {
    return new TxtKVZ();
  }

  /**
   * Create an instance of {@link VypisRZZ }
   */
  public VypisRZZ createVypisRZZ() {
    return new VypisRZZ();
  }

  /**
   * Create an instance of {@link SpolecniciSVkladem }
   */
  public SpolecniciSVkladem createSpolecniciSVkladem() {
    return new SpolecniciSVkladem();
  }

  /**
   * Create an instance of {@link AdresaDorucovaci }
   */
  public AdresaDorucovaci createAdresaDorucovaci() {
    return new AdresaDorucovaci();
  }

  /**
   * Create an instance of {@link KodNace }
   */
  public KodNace createKodNace() {
    return new KodNace();
  }

  /**
   * Create an instance of {@link ObecRFO }
   */
  public ObecRFO createObecRFO() {
    return new ObecRFO();
  }

  /**
   * Create an instance of {@link KUpadce }
   */
  public KUpadce createKUpadce() {
    return new KUpadce();
  }

  /**
   * Create an instance of {@link StadrsOdpoved }
   */
  public StadrsOdpoved createStadrsOdpoved() {
    return new StadrsOdpoved();
  }

  /**
   * Create an instance of {@link ZakladateleSP }
   */
  public ZakladateleSP createZakladateleSP() {
    return new ZakladateleSP();
  }

  /**
   * Create an instance of {@link PravnickaOsoba }
   */
  public PravnickaOsoba createPravnickaOsoba() {
    return new PravnickaOsoba();
  }

  /**
   * Create an instance of {@link OrganFO }
   */
  public OrganFO createOrganFO() {
    return new OrganFO();
  }

  /**
   * Create an instance of {@link VedOz }
   */
  public VedOz createVedOz() {
    return new VedOz();
  }

  /**
   * Create an instance of {@link PravniFormaRZP }
   */
  public PravniFormaRZP createPravniFormaRZP() {
    return new PravniFormaRZP();
  }

  /**
   * Create an instance of {@link ClenoveSdruzeni }
   */
  public ClenoveSdruzeni createClenoveSdruzeni() {
    return new ClenoveSdruzeni();
  }

  /**
   * Create an instance of {@link SpravniRada }
   */
  public SpravniRada createSpravniRada() {
    return new SpravniRada();
  }

  /**
   * Create an instance of {@link Registrace }
   */
  public Registrace createRegistrace() {
    return new Registrace();
  }

  /**
   * Create an instance of {@link Komplementari }
   */
  public Komplementari createKomplementari() {
    return new Komplementari();
  }

  /**
   * Create an instance of {@link KodOkec }
   */
  public KodOkec createKodOkec() {
    return new KodOkec();
  }

  /**
   * Create an instance of {@link PrazskyObvodRFO }
   */
  public PrazskyObvodRFO createPrazskyObvodRFO() {
    return new PrazskyObvodRFO();
  }

  /**
   * Create an instance of {@link Soud }
   */
  public Soud createSoud() {
    return new Soud();
  }

  /**
   * Create an instance of {@link CiziNazev }
   */
  public CiziNazev createCiziNazev() {
    return new CiziNazev();
  }

  /**
   * Create an instance of {@link ZivnostiRZP }
   */
  public ZivnostiRZP createZivnostiRZP() {
    return new ZivnostiRZP();
  }

  /**
   * Create an instance of {@link StatutarniOrgan }
   */
  public StatutarniOrgan createStatutarniOrgan() {
    return new StatutarniOrgan();
  }

  /**
   * Create an instance of {@link OdpovedCEU }
   */
  public OdpovedCEU createOdpovedCEU() {
    return new OdpovedCEU();
  }

  /**
   * Create an instance of {@link OdpovedBasic }
   */
  public OdpovedBasic createOdpovedBasic() {
    return new OdpovedBasic();
  }

  /**
   * Create an instance of {@link Rozhodnuti }
   */
  public Rozhodnuti createRozhodnuti() {
    return new Rozhodnuti();
  }

  /**
   * Create an instance of {@link RegistraceRCNS }
   */
  public RegistraceRCNS createRegistraceRCNS() {
    return new RegistraceRCNS();
  }

  /**
   * Create an instance of {@link PredmetyPodnikani }
   */
  public PredmetyPodnikani createPredmetyPodnikani() {
    return new PredmetyPodnikani();
  }

  /**
   * Create an instance of {@link ZivnostenskyUrad }
   */
  public ZivnostenskyUrad createZivnostenskyUrad() {
    return new ZivnostenskyUrad();
  }

  /**
   * Create an instance of {@link Komanditiste }
   */
  public Komanditiste createKomanditiste() {
    return new Komanditiste();
  }

  /**
   * Create an instance of {@link AdresaUIR }
   */
  public AdresaUIR createAdresaUIR() {
    return new AdresaUIR();
  }

  /**
   * Create an instance of {@link XsltErrorList.E }
   */
  public XsltErrorList.E createXsltErrorListE() {
    return new XsltErrorList.E();
  }

  /**
   * Create an instance of {@link Akcie.EM }
   */
  public Akcie.EM createAkcieEM() {
    return new Akcie.EM();
  }

  /**
   * Create an instance of {@link OdstepneZavody.OZ }
   */
  public OdstepneZavody.OZ createOdstepneZavodyOZ() {
    return new OdstepneZavody.OZ();
  }

  /**
   * Create an instance of {@link KonkurzyVyrovnani.Ukon }
   */
  public KonkurzyVyrovnani.Ukon createKonkurzyVyrovnaniUkon() {
    return new KonkurzyVyrovnani.Ukon();
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link XsltErrorList }{@code >}}
   */
  @XmlElementDecl(namespace = "http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3", name = "E_list")
  public JAXBElement<XsltErrorList> createEList(XsltErrorList value) {
    return new JAXBElement<XsltErrorList>(_EList_QNAME, XsltErrorList.class, null, value);
  }

}
