//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 11:04:38 AM CEST 
//


package cz.petrbalat.xml.ares;

import javax.xml.bind.annotation.*;


/**
 * Obor činnosti (od 1.7.2008)
 *
 * <p>Java class for obor_cinnosti complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="obor_cinnosti">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="K" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}kod_oboru" minOccurs="0"/>
 *         &lt;element name="T" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="aktivni" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}ano_ne" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "obor_cinnosti", propOrder = {
  "k",
  "t"
})
public class OborCinnosti {

  @XmlElement(name = "K")
  protected String k;
  @XmlElement(name = "T")
  protected String t;
  @XmlAttribute(name = "aktivni")
  protected String aktivni;

  /**
   * Gets the value of the k property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getK() {
    return k;
  }

  /**
   * Sets the value of the k property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setK(String value) {
    this.k = value;
  }

  /**
   * Gets the value of the t property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getT() {
    return t;
  }

  /**
   * Sets the value of the t property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setT(String value) {
    this.t = value;
  }

  /**
   * Gets the value of the aktivni property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getAktivni() {
    return aktivni;
  }

  /**
   * Sets the value of the aktivni property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setAktivni(String value) {
    this.aktivni = value;
  }

}
