//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 11:04:38 AM CEST 
//


package cz.petrbalat.xml.ares;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for odstepne_zavody complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="odstepne_zavody">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OZ" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ICO" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}ico" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="OF" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}obchodni_firma" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="SI" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}adresa_ARES" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="CIN" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}cinnosti" minOccurs="0"/>
 *                   &lt;element name="V" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}angazma" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="dod" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                 &lt;attribute name="ddo" type="{http://www.w3.org/2001/XMLSchema}date" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "odstepne_zavody", propOrder = {
  "oz"
})
public class OdstepneZavody {

  @XmlElement(name = "OZ", required = true)
  protected List<OdstepneZavody.OZ> oz;

  /**
   * Gets the value of the oz property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the JAXB object.
   * This is why there is not a <CODE>set</CODE> method for the oz property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   * <pre>
   *    getOZ().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link OdstepneZavody.OZ }
   */
  public List<OdstepneZavody.OZ> getOZ() {
    if (oz == null) {
      oz = new ArrayList<OdstepneZavody.OZ>();
    }
    return this.oz;
  }


  /**
   * <p>Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="ICO" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}ico" maxOccurs="unbounded" minOccurs="0"/>
   *         &lt;element name="OF" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}obchodni_firma" maxOccurs="unbounded" minOccurs="0"/>
   *         &lt;element name="SI" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}adresa_ARES" maxOccurs="unbounded" minOccurs="0"/>
   *         &lt;element name="CIN" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}cinnosti" minOccurs="0"/>
   *         &lt;element name="V" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}angazma" maxOccurs="unbounded" minOccurs="0"/>
   *       &lt;/sequence>
   *       &lt;attribute name="dod" type="{http://www.w3.org/2001/XMLSchema}date" />
   *       &lt;attribute name="ddo" type="{http://www.w3.org/2001/XMLSchema}date" />
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
    "ico",
    "of",
    "si",
    "cin",
    "v"
  })
  public static class OZ {

    @XmlElement(name = "ICO")
    protected List<Ico> ico;
    @XmlElement(name = "OF")
    protected List<ObchodniFirma> of;
    @XmlElement(name = "SI")
    protected List<AdresaARES> si;
    @XmlElement(name = "CIN")
    protected Cinnosti cin;
    @XmlElement(name = "V")
    protected List<Angazma> v;
    @XmlAttribute(name = "dod")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dod;
    @XmlAttribute(name = "ddo")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar ddo;

    /**
     * Gets the value of the ico property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ico property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getICO().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ico }
     */
    public List<Ico> getICO() {
      if (ico == null) {
        ico = new ArrayList<Ico>();
      }
      return this.ico;
    }

    /**
     * Gets the value of the of property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the of property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOF().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObchodniFirma }
     */
    public List<ObchodniFirma> getOF() {
      if (of == null) {
        of = new ArrayList<ObchodniFirma>();
      }
      return this.of;
    }

    /**
     * Gets the value of the si property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the si property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSI().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdresaARES }
     */
    public List<AdresaARES> getSI() {
      if (si == null) {
        si = new ArrayList<AdresaARES>();
      }
      return this.si;
    }

    /**
     * Gets the value of the cin property.
     *
     * @return possible object is
     * {@link Cinnosti }
     */
    public Cinnosti getCIN() {
      return cin;
    }

    /**
     * Sets the value of the cin property.
     *
     * @param value allowed object is
     *              {@link Cinnosti }
     */
    public void setCIN(Cinnosti value) {
      this.cin = value;
    }

    /**
     * Gets the value of the v property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the v property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getV().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Angazma }
     */
    public List<Angazma> getV() {
      if (v == null) {
        v = new ArrayList<Angazma>();
      }
      return this.v;
    }

    /**
     * Gets the value of the dod property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getDod() {
      return dod;
    }

    /**
     * Sets the value of the dod property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setDod(XMLGregorianCalendar value) {
      this.dod = value;
    }

    /**
     * Gets the value of the ddo property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getDdo() {
      return ddo;
    }

    /**
     * Sets the value of the ddo property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setDdo(XMLGregorianCalendar value) {
      this.ddo = value;
    }

  }

}
