//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 11:04:38 AM CEST 
//


package cz.petrbalat.xml.ares;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * Údaje fyzické osoby v RCNS
 *
 * <p>Java class for organ_FO complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="organ_FO">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Nazev_organu" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3}popis" minOccurs="0"/>
 *         &lt;element name="Poznamka" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3}popis" minOccurs="0"/>
 *         &lt;element name="TP" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3}titul_pred" minOccurs="0"/>
 *         &lt;element name="J" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3}jmeno" minOccurs="0"/>
 *         &lt;element name="P" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3}prijmeni" minOccurs="0"/>
 *         &lt;element name="Rodne_prijmeni" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3}prijmeni" minOccurs="0"/>
 *         &lt;element name="TZ" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3}titul_za" minOccurs="0"/>
 *         &lt;element name="A" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}adresa_ARES" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="dod" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="ddo" type="{http://www.w3.org/2001/XMLSchema}date" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "organ_FO", propOrder = {
  "nazevOrganu",
  "poznamka",
  "tp",
  "j",
  "p",
  "rodnePrijmeni",
  "tz",
  "a"
})
public class OrganFO {

  @XmlElement(name = "Nazev_organu")
  protected String nazevOrganu;
  @XmlElement(name = "Poznamka")
  protected String poznamka;
  @XmlElement(name = "TP")
  protected String tp;
  @XmlElement(name = "J")
  protected String j;
  @XmlElement(name = "P")
  protected String p;
  @XmlElement(name = "Rodne_prijmeni")
  protected String rodnePrijmeni;
  @XmlElement(name = "TZ")
  protected String tz;
  @XmlElement(name = "A")
  protected List<AdresaARES> a;
  @XmlAttribute(name = "dod")
  @XmlSchemaType(name = "date")
  protected XMLGregorianCalendar dod;
  @XmlAttribute(name = "ddo")
  @XmlSchemaType(name = "date")
  protected XMLGregorianCalendar ddo;

  /**
   * Gets the value of the nazevOrganu property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getNazevOrganu() {
    return nazevOrganu;
  }

  /**
   * Sets the value of the nazevOrganu property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setNazevOrganu(String value) {
    this.nazevOrganu = value;
  }

  /**
   * Gets the value of the poznamka property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getPoznamka() {
    return poznamka;
  }

  /**
   * Sets the value of the poznamka property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setPoznamka(String value) {
    this.poznamka = value;
  }

  /**
   * Gets the value of the tp property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getTP() {
    return tp;
  }

  /**
   * Sets the value of the tp property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setTP(String value) {
    this.tp = value;
  }

  /**
   * Gets the value of the j property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getJ() {
    return j;
  }

  /**
   * Sets the value of the j property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setJ(String value) {
    this.j = value;
  }

  /**
   * Gets the value of the p property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getP() {
    return p;
  }

  /**
   * Sets the value of the p property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setP(String value) {
    this.p = value;
  }

  /**
   * Gets the value of the rodnePrijmeni property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getRodnePrijmeni() {
    return rodnePrijmeni;
  }

  /**
   * Sets the value of the rodnePrijmeni property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setRodnePrijmeni(String value) {
    this.rodnePrijmeni = value;
  }

  /**
   * Gets the value of the tz property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getTZ() {
    return tz;
  }

  /**
   * Sets the value of the tz property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setTZ(String value) {
    this.tz = value;
  }

  /**
   * Gets the value of the a property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the JAXB object.
   * This is why there is not a <CODE>set</CODE> method for the a property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   * <pre>
   *    getA().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link AdresaARES }
   */
  public List<AdresaARES> getA() {
    if (a == null) {
      a = new ArrayList<AdresaARES>();
    }
    return this.a;
  }

  /**
   * Gets the value of the dod property.
   *
   * @return possible object is
   * {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getDod() {
    return dod;
  }

  /**
   * Sets the value of the dod property.
   *
   * @param value allowed object is
   *              {@link XMLGregorianCalendar }
   */
  public void setDod(XMLGregorianCalendar value) {
    this.dod = value;
  }

  /**
   * Gets the value of the ddo property.
   *
   * @return possible object is
   * {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getDdo() {
    return ddo;
  }

  /**
   * Sets the value of the ddo property.
   *
   * @param value allowed object is
   *              {@link XMLGregorianCalendar }
   */
  public void setDdo(XMLGregorianCalendar value) {
    this.ddo = value;
  }

}
