//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 11:04:38 AM CEST 
//


package cz.petrbalat.xml.ares;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Spisová značka, pod kterou je veden spis subjektu u daného soudu. (Bývá zapisována oddíl / vložka.)
 *
 * <p>Java class for spisova_znacka complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="spisova_znacka">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SD" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}soud"/>
 *         &lt;element name="OV" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3}popis"/>
 *       &lt;/sequence>
 *       &lt;attribute name="dod" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="ddo" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="zdroj" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}zdroj_type" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "spisova_znacka", propOrder = {
  "sd",
  "ov"
})
public class SpisovaZnacka {

  @XmlElement(name = "SD", required = true)
  protected Soud sd;
  @XmlElement(name = "OV", required = true)
  protected String ov;
  @XmlAttribute(name = "dod")
  @XmlSchemaType(name = "date")
  protected XMLGregorianCalendar dod;
  @XmlAttribute(name = "ddo")
  @XmlSchemaType(name = "date")
  protected XMLGregorianCalendar ddo;
  @XmlAttribute(name = "zdroj")
  protected ZdrojType zdroj;

  /**
   * Gets the value of the sd property.
   *
   * @return possible object is
   * {@link Soud }
   */
  public Soud getSD() {
    return sd;
  }

  /**
   * Sets the value of the sd property.
   *
   * @param value allowed object is
   *              {@link Soud }
   */
  public void setSD(Soud value) {
    this.sd = value;
  }

  /**
   * Gets the value of the ov property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getOV() {
    return ov;
  }

  /**
   * Sets the value of the ov property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setOV(String value) {
    this.ov = value;
  }

  /**
   * Gets the value of the dod property.
   *
   * @return possible object is
   * {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getDod() {
    return dod;
  }

  /**
   * Sets the value of the dod property.
   *
   * @param value allowed object is
   *              {@link XMLGregorianCalendar }
   */
  public void setDod(XMLGregorianCalendar value) {
    this.dod = value;
  }

  /**
   * Gets the value of the ddo property.
   *
   * @return possible object is
   * {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getDdo() {
    return ddo;
  }

  /**
   * Sets the value of the ddo property.
   *
   * @param value allowed object is
   *              {@link XMLGregorianCalendar }
   */
  public void setDdo(XMLGregorianCalendar value) {
    this.ddo = value;
  }

  /**
   * Gets the value of the zdroj property.
   *
   * @return possible object is
   * {@link ZdrojType }
   */
  public ZdrojType getZdroj() {
    return zdroj;
  }

  /**
   * Sets the value of the zdroj property.
   *
   * @param value allowed object is
   *              {@link ZdrojType }
   */
  public void setZdroj(ZdrojType value) {
    this.zdroj = value;
  }

}
