//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 11:04:38 AM CEST 
//


package cz.petrbalat.xml.ares;

import javax.xml.bind.annotation.*;


/**
 * z Hlavní tabulky úpadců - slouží zejména pro rozlišení, o jakého úpadce se jedná
 *
 * <p>Java class for stav_subjektu_ceu complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="stav_subjektu_ceu">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SKO" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}stav_upadce_CEU"/>
 *         &lt;element name="SVY" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}stav_upadce_CEU"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stav_subjektu_ceu", propOrder = {
  "sko",
  "svy"
})
public class StavSubjektuCeu {

  @XmlElement(name = "SKO", required = true)
  @XmlSchemaType(name = "string")
  protected StavUpadceCEU sko;
  @XmlElement(name = "SVY", required = true)
  @XmlSchemaType(name = "string")
  protected StavUpadceCEU svy;

  /**
   * Gets the value of the sko property.
   *
   * @return possible object is
   * {@link StavUpadceCEU }
   */
  public StavUpadceCEU getSKO() {
    return sko;
  }

  /**
   * Sets the value of the sko property.
   *
   * @param value allowed object is
   *              {@link StavUpadceCEU }
   */
  public void setSKO(StavUpadceCEU value) {
    this.sko = value;
  }

  /**
   * Gets the value of the svy property.
   *
   * @return possible object is
   * {@link StavUpadceCEU }
   */
  public StavUpadceCEU getSVY() {
    return svy;
  }

  /**
   * Sets the value of the svy property.
   *
   * @param value allowed object is
   *              {@link StavUpadceCEU }
   */
  public void setSVY(StavUpadceCEU value) {
    this.svy = value;
  }

}
