//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 11:04:38 AM CEST 
//


package cz.petrbalat.xml.ares;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for textType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="textType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/uvis_datatypes/v_1.0.3>text">
 *       &lt;attribute name="dod" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="ddo" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="zdroj" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}zdroj_type" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "textType", propOrder = {
  "value"
})
public class TextType {

  @XmlValue
  protected String value;
  @XmlAttribute(name = "dod")
  @XmlSchemaType(name = "date")
  protected XMLGregorianCalendar dod;
  @XmlAttribute(name = "ddo")
  @XmlSchemaType(name = "date")
  protected XMLGregorianCalendar ddo;
  @XmlAttribute(name = "zdroj")
  protected ZdrojType zdroj;

  /**
   * Obecný popis formou textu: jedná se o obecný text, který bývá formátován do řádků, kdy je třeba toto formátování do řádků zachovat a doporučuje se prezentovat text s využitím neproporcionálního písma.
   *
   * @return possible object is
   * {@link String }
   */
  public String getValue() {
    return value;
  }

  /**
   * Sets the value of the value property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setValue(String value) {
    this.value = value;
  }

  /**
   * Gets the value of the dod property.
   *
   * @return possible object is
   * {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getDod() {
    return dod;
  }

  /**
   * Sets the value of the dod property.
   *
   * @param value allowed object is
   *              {@link XMLGregorianCalendar }
   */
  public void setDod(XMLGregorianCalendar value) {
    this.dod = value;
  }

  /**
   * Gets the value of the ddo property.
   *
   * @return possible object is
   * {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getDdo() {
    return ddo;
  }

  /**
   * Sets the value of the ddo property.
   *
   * @param value allowed object is
   *              {@link XMLGregorianCalendar }
   */
  public void setDdo(XMLGregorianCalendar value) {
    this.ddo = value;
  }

  /**
   * Gets the value of the zdroj property.
   *
   * @return possible object is
   * {@link ZdrojType }
   */
  public ZdrojType getZdroj() {
    return zdroj;
  }

  /**
   * Sets the value of the zdroj property.
   *
   * @param value allowed object is
   *              {@link ZdrojType }
   */
  public void setZdroj(ZdrojType value) {
    this.zdroj = value;
  }

}
