//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 11:04:38 AM CEST 
//


package cz.petrbalat.xml.ares;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Datumy začátku a konce členství v orgánu pro členy dozorčích rad a statutárních orgánů
 *
 * <p>Java class for trvani complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="trvani">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DZA" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="DK" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "trvani", propOrder = {
  "dza",
  "dk"
})
public class Trvani {

  @XmlElement(name = "DZA")
  @XmlSchemaType(name = "date")
  protected XMLGregorianCalendar dza;
  @XmlElement(name = "DK")
  @XmlSchemaType(name = "date")
  protected XMLGregorianCalendar dk;

  /**
   * Gets the value of the dza property.
   *
   * @return possible object is
   * {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getDZA() {
    return dza;
  }

  /**
   * Sets the value of the dza property.
   *
   * @param value allowed object is
   *              {@link XMLGregorianCalendar }
   */
  public void setDZA(XMLGregorianCalendar value) {
    this.dza = value;
  }

  /**
   * Gets the value of the dk property.
   *
   * @return possible object is
   * {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getDK() {
    return dk;
  }

  /**
   * Sets the value of the dk property.
   *
   * @param value allowed object is
   *              {@link XMLGregorianCalendar }
   */
  public void setDK(XMLGregorianCalendar value) {
    this.dk = value;
  }

}
