//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 11:04:38 AM CEST 
//


package cz.petrbalat.xml.ares;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * Společné údaje o konkurzu, vyrovnání nebo zamítnutí konkurzu (K, V nebo Z)
 *
 * <p>Java class for txt_KVZ complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="txt_KVZ">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DVE" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="T" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}textType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "txt_KVZ", propOrder = {
  "dve",
  "t"
})
public class TxtKVZ {

  @XmlElement(name = "DVE")
  @XmlSchemaType(name = "date")
  protected XMLGregorianCalendar dve;
  @XmlElement(name = "T")
  protected List<TextType> t;

  /**
   * Gets the value of the dve property.
   *
   * @return possible object is
   * {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getDVE() {
    return dve;
  }

  /**
   * Sets the value of the dve property.
   *
   * @param value allowed object is
   *              {@link XMLGregorianCalendar }
   */
  public void setDVE(XMLGregorianCalendar value) {
    this.dve = value;
  }

  /**
   * Gets the value of the t property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the JAXB object.
   * This is why there is not a <CODE>set</CODE> method for the t property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   * <pre>
   *    getT().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link TextType }
   */
  public List<TextType> getT() {
    if (t == null) {
      t = new ArrayList<TextType>();
    }
    return this.t;
  }

}
