//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 11:04:38 AM CEST 
//


package cz.petrbalat.xml.ares;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tzu_osoba.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tzu_osoba">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="T"/>
 *     &lt;enumeration value="Z"/>
 *     &lt;enumeration value="U"/>
 *     &lt;enumeration value="E"/>
 *     &lt;enumeration value="Tuzemská"/>
 *     &lt;enumeration value="Zahraniční"/>
 *     &lt;enumeration value="Uprchlík"/>
 *     &lt;enumeration value="Evropská"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "tzu_osoba")
@XmlEnum
public enum TzuOsoba {

  T("T"),
  Z("Z"),
  U("U"),
  E("E"),
  @XmlEnumValue("Tuzemsk\u00e1")
  TUZEMSKÁ("Tuzemsk\u00e1"),
  @XmlEnumValue("Zahrani\u010dn\u00ed")
  ZAHRANIČNÍ("Zahrani\u010dn\u00ed"),
  @XmlEnumValue("Uprchl\u00edk")
  UPRCHLÍK("Uprchl\u00edk"),
  @XmlEnumValue("Evropsk\u00e1")
  EVROPSKÁ("Evropsk\u00e1");
  private final String value;

  TzuOsoba(String v) {
    value = v;
  }

  public static TzuOsoba fromValue(String v) {
    for (TzuOsoba c : TzuOsoba.values()) {
      if (c.value.equals(v)) {
        return c;
      }
    }
    throw new IllegalArgumentException(v);
  }

  public String value() {
    return value;
  }

}
