//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 11:04:38 AM CEST 
//


package cz.petrbalat.xml.ares;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * Výpis z Registru církví a náboženských společností v ARES
 *
 * <p>Java class for vypis_CNS complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="vypis_CNS">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UVOD" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}uvod" minOccurs="0"/>
 *         &lt;element name="CNS" type="{http://wwwinfo.mfcr.cz/ares/xml_doc/schemas/ares/ares_datatypes/v_1.0.3}zakladni_udaje_CNS" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vypis_CNS", propOrder = {
  "uvod",
  "cns"
})
public class VypisCNS {

  @XmlElement(name = "UVOD")
  protected Uvod uvod;
  @XmlElement(name = "CNS")
  protected List<ZakladniUdajeCNS> cns;

  /**
   * Gets the value of the uvod property.
   *
   * @return possible object is
   * {@link Uvod }
   */
  public Uvod getUVOD() {
    return uvod;
  }

  /**
   * Sets the value of the uvod property.
   *
   * @param value allowed object is
   *              {@link Uvod }
   */
  public void setUVOD(Uvod value) {
    this.uvod = value;
  }

  /**
   * Gets the value of the cns property.
   *
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the JAXB object.
   * This is why there is not a <CODE>set</CODE> method for the cns property.
   *
   * <p>
   * For example, to add a new item, do as follows:
   * <pre>
   *    getCNS().add(newItem);
   * </pre>
   *
   *
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link ZakladniUdajeCNS }
   */
  public List<ZakladniUdajeCNS> getCNS() {
    if (cns == null) {
      cns = new ArrayList<ZakladniUdajeCNS>();
    }
    return this.cns;
  }

}
